name: Python Unit tests

on:
  pull_request:
    branches: [ test ]

jobs:
  test:
    runs-on: macos-latest  # Specify macOS as the runner
    steps:
    - uses: actions/checkout@v2
    - name: Install Python dependencies
      run: |
        python3 -m ensurepip --upgrade
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
